---
title: "Final Models"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(GGally) # ggpairs
library(modelr) # add_residuals and add_predictions
library(ggfortify) # autoplot
library(broom) # glance - for checking AIC, BIC of models
```


```{r}
activity_hb <- read_csv(here("clean_data/activity_hb.csv")) 
mortality_hb <- read_csv(here("clean_data/mortality_hb.csv")) 
```


```{r}
activity_hb_for_fitting_easr <- activity_hb %>% 
# convert financial year to numeric year so it can be used in model
    mutate(start_fin_year = as.numeric(str_extract(financial_year, "^[0-9]{4}")), 
         .after = financial_year) %>% 
  select(-financial_year, -hbr, -crude_rate, -number_of_discharges) %>% 
  # Remove all rows which are combinations of other rows
  filter(hbr_name != "Scotland",
         admission_type != "All",
         !age %in% c("All", "under 75"),
         sex != "All",
         diagnosis != "Cerebrovascular Disease") 
```


```{r}
mortality_hb_for_fitting_easr <- mortality_hb %>% 
  select(-hbr, -crude_rate, -number_of_deaths) %>% 
  # Remove all rows which are combinations of other rows
  filter(hbr_name != "Scotland",
         !age %in% c("All", "under 75"),
         sex != "All",
         diagnosis != "Cerebrovascular Disease") 
```


```{r}
discharge_model <- lm(log(1 + easr) ~ diagnosis + age + admission_type + 
                        hbr_name + sex + start_fin_year + 
                    admission_type:diagnosis +
                    age:admission_type + 
                    age:diagnosis + 
                    age:diagnosis:admission_type + 
                    sex:diagnosis, 
                    data = activity_hb_for_fitting_easr)
```


```{r}
mortality_model <- lm(log(1 + easr) ~ age + diagnosis + hbr_name + year + sex +
                      age:diagnosis, 
                      data = mortality_hb_for_fitting_easr)
```


Need to decide how we want to display results for presentation. 



