---
title: "Geospatial Analysis"
output:
  html_document:
    toc: yes
    toc_float: true
    toc_depth: '2'
    highlight: tango
    df_print: paged
---


```{r}
library(sf)
library(leaflet)
library(tidyverse)
library(htmlwidgets)
```

## Adding health board data to shapefile

```{r}
activity_hb <- read_csv(here("clean_data/activity_hb.csv"))
mortality_hb <- read_csv(here("clean_data/mortality_hb.csv")) 

# simplified shapefile created for group project
scot_hb_shapefile <- st_read(
  here::here("map_files/health_board_shapefile_scotland/scot_hb_shapefile_simplified.shp"))
```

## Adding health board data to shapefile

```{r}
# Adding discharge data to shapefile
discharge_hb_totals <- activity_hb %>% 
  filter(hbr != "S92000003",
         sex == "All",
         admission_type == "All",
         age == "All", 
         diagnosis == "Cerebrovascular Disease",
         financial_year == "2021/22") %>% 
  select(-c("financial_year", "hbr", "admission_type", "age", "sex", "diagnosis")) %>% 
  mutate(hbr_name = recode(hbr_name, "Ayrshire & Arran" = "Ayrshire and Arran",
                           "Dumfries & Galloway" = "Dumfries and Galloway",
                           "Greater Glasgow & Clyde" = "Greater Glasgow and Clyde")) %>% 
  rename("discharge_crude_rate" = "crude_rate",
         "discharge_easr" = "easr")

# Combining island data

island_averages_disch <- discharge_hb_totals %>% 
  filter(hbr_name %in% c("Orkney", "Shetland", "Western Isles")) %>% 
  summarise(number_of_discharges = mean(number_of_discharges), 
            discharge_crude_rate = mean(discharge_crude_rate), 
            discharge_easr = mean(discharge_easr))  
  
hbr_name <- c("Orkney", "Shetland", "Western Isles")

island_averages_disch <- island_averages_disch %>% 
  slice(rep(1, each = 3)) %>% 
  cbind(hbr_name)

discharge_hb_totals <- discharge_hb_totals %>% 
  filter(!hbr_name %in% c("Orkney", "Shetland", "Western Isles")) %>% 
  rbind(island_averages_disch)

# Adding discharge data to shapefile

sf_hb_stroke_data <- left_join(scot_hb_shapefile, discharge_hb_totals, by = c("HBName" = "hbr_name"))

# Adding mortality data to shapefile
mortality_hb_totals <- mortality_hb %>% 
  filter(hbr != "S92000003",
         sex == "All",
         age == "All", 
         diagnosis == "Cerebrovascular Disease",
         year == 2021) %>% 
  select(-c("year", "hbr", "age", "sex", "diagnosis")) %>% 
  mutate(hbr_name = recode(hbr_name, "Ayrshire & Arran" = "Ayrshire and Arran",
                           "Dumfries & Galloway" = "Dumfries and Galloway",
                           "Greater Glasgow & Clyde" = "Greater Glasgow and Clyde")) %>%   rename("mortality_crude_rate" = "crude_rate",
         "mortality_easr" = "easr")

# Combining island data
island_averages_mort <- mortality_hb_totals %>% 
  filter(hbr_name %in% c("Orkney", "Shetland", "Western Isles")) %>% 
  summarise(number_of_deaths = mean(number_of_deaths), 
            mortality_crude_rate = mean(mortality_crude_rate), 
            mortality_easr = mean(mortality_easr))  

island_averages_mort <- island_averages_mort %>% 
  slice(rep(1, each = 3)) %>% 
  cbind(hbr_name)

mortality_hb_totals <- mortality_hb_totals %>% 
  filter(!hbr_name %in% c("Orkney", "Shetland", "Western Isles")) %>% 
  rbind(island_averages_mort)

# Adding mortality data to shapefile

sf_hb_discharge_mort_data <- left_join(sf_hb_stroke_data, mortality_hb_totals, 
                             by = c("HBName" = "hbr_name")) %>% 
# Need to round all values so lots of decimal places don't appear in tooltip on map
  mutate(number_of_discharges = round(number_of_discharges, 0),
    discharge_crude_rate = round(discharge_crude_rate, 0),
         discharge_easr = round(discharge_easr, 0),
    number_of_deaths = round(number_of_deaths, 0),
         mortality_crude_rate = round(mortality_crude_rate, 0),
         mortality_easr = round(mortality_easr, 0))

#rm(activity_hb, discharge_hb_totals, mortality_hb, mortality_hb_totals,
#   scot_hb_shapefile, sf_hb_stroke_data, island_averages_disch, hbr_name,
#   island_averages_mort)

#st_write(sf_hb_discharge_mort_data, 
#         here("map_files/sf_hb_discharge_mort.shp"), 
#         driver="ESRI Shapefile",
#         append = FALSE)

```


## Adding council data to shapefile



```{r}

# Prepare the text for tooltips:
mytext_dis_hb <- paste(
    "Health Board: ", sf_hb_discharge_mort_data$HBName,"<br/>", 
    "EASR: ", sf_hb_discharge_mort_data$discharge_easr, "<br/>", 
    sep="") %>%
  lapply(htmltools::HTML)

# originally used colorQuantile but colorNumeric creates a continuous color range 
# for continous input which is what we have. 
pal_dis_hb <- colorNumeric(
  palette = "Purples",
  domain = sf_hb_discharge_mort_data$discharge_easr)

discharge_hb_easr <- leaflet(sf_hb_discharge_mort_data) %>% 
  addTiles()  %>% 
  setView( lat=57, lng=-5 , zoom=6) %>%
  addPolygons(stroke = TRUE, 
              color = "black", 
              weight = 1,
              fillOpacity = 0.8, 
    #          smoothFactor = 0.5, 
    #          fillColor = ~colorQuantile("Purples", easr)(easr) ,
              fillColor = ~pal_dis_hb(discharge_easr),
    label = mytext_dis_hb,
    labelOptions = labelOptions( 
      style = list("font-weight" = "normal", padding = "3px 8px"), 
      textsize = "13px", 
      direction = "auto",
      opacity = 0.75))

discharge_hb_easr 

# save the widget in a html file if needed.
saveWidget(discharge_hb_easr, here("map_files/discharge_hb_easr.html"))

# For fill colours
# http://www.sthda.com/english/wiki/colors-in-r
```



## Council - Discharges

```{r}
activity_ca <- read_csv(here("clean_data/activity_ca.csv"))

council_sf <- st_read(here::here("map_files/council_shapefile_scotland/pub_las.shp"))

council_sf <- st_transform(council_sf, "+proj=longlat +ellps=WGS84 +datum=WGS84")

council_sf_simplified <- rmapshaper::ms_simplify(input = council_sf,
                                           keep = 0.001,
                                           keep_shapes = TRUE)

rm(council_sf)
```



```{r}
discharge_ca_totals <- activity_ca %>% 
  filter(ca != "S92000003",
         sex == "All",
         age == "All", 
         admission_type == "All",
         diagnosis == "Cerebrovascular Disease",
         financial_year == "2021/22") %>% 
  select(-c("financial_year", "ca","age", "admission_type", "sex", "diagnosis",
            "hb", "hb_name")) %>% 
  mutate(ca_name = recode(ca_name, "Na h-Eileanan Siar" = "Eilean Siar"))

sf_ca_stroke_data <- left_join(council_sf_simplified, discharge_ca_totals, 
                                    by = c("local_auth" = "ca_name"))

rm(activity_ca, discharge_ca_totals, council_sf_simplified)
```


```{r}
mytext_dis_ca <- paste(
    "Council Area: ", sf_ca_stroke_data$local_aut,"<br/>", 
    "EASR: ", sf_ca_stroke_data$easr, "<br/>", 
    sep="") %>%
  lapply(htmltools::HTML)

pal_dis_ca <- colorNumeric(
  palette = "Purples",
  domain = sf_ca_stroke_data$easr)

discharge_ca_easr <- leaflet(sf_ca_stroke_data) %>% 
  addTiles()  %>% 
  setView( lat=57, lng=-5 , zoom=6) %>%
  addPolygons(stroke = TRUE, 
              color = "black", 
              weight = 1,
              fillOpacity = 0.8, 
              fillColor = ~pal_dis_ca(easr),
    label = mytext_dis_ca,
    labelOptions = labelOptions( 
      style = list("font-weight" = "normal", padding = "3px 8px"), 
      textsize = "13px", 
      direction = "auto",
      opacity = 0.75))

discharge_ca_easr

saveWidget(discharge_ca_easr, here("map_files/discharge_ca_easr.html"))
```

## Health Board - Deaths


```{r}
mortality_hb <- read_csv(here("clean_data/mortality_hb.csv")) 
```


```{r}
mortality_hb_totals <- mortality_hb %>% 
  filter(hbr != "S92000003",
         sex == "All",
         age == "All", 
         diagnosis == "Cerebrovascular Disease",
         year == 2021) %>% 
  select(-c("year", "hbr", "age", "sex", "diagnosis")) %>% 
  mutate(hbr_name = recode(hbr_name, "Ayrshire & Arran" = "Ayrshire and Arran",
                           "Dumfries & Galloway" = "Dumfries and Galloway",
                           "Greater Glasgow & Clyde" = "Greater Glasgow and Clyde"))

sf_hb_mort_data <- left_join(scot_hb_shapefile, mortality_hb_totals, 
                             by = c("HBName" = "hbr_name")) %>% 
  mutate(crude_rate = round(crude_rate, 0),
         easr = round(easr, 0))

rm(mortality_hb, mortality_hb_totals)
```


```{r}
# Prepare the text for tooltips:
mytext_mort_hb <- paste(
    "Health Board: ", sf_hb_mort_data$HBName,"<br/>", 
    "EASR: ", sf_hb_mort_data$easr, "<br/>", 
    "Deaths: ", sf_hb_mort_data$number_of_deaths, 
    sep="") %>%
  lapply(htmltools::HTML)

# originally used colorQuantile but colorNumeric creates a continuous color range 
# for continuous input which is what we have. 
pal_mort_hb <- colorNumeric(
  palette = "Purples",
  domain = sf_hb_mort_data$easr)

mort_hb_easr <- leaflet(sf_hb_mort_data) %>% 
  addTiles()  %>% 
  setView( lat=57, lng=-5 , zoom=6) %>%
  addPolygons(stroke = TRUE, 
              color = "black", 
              weight = 1,
              fillOpacity = 0.8, 
    #          smoothFactor = 0.5, 
    #          fillColor = ~colorQuantile("Purples", easr)(easr) ,
              fillColor = ~pal_mort_hb(easr),
    label = mytext_mort_hb,
    labelOptions = labelOptions( 
      style = list("font-weight" = "normal", padding = "3px 8px"), 
      textsize = "13px", 
      direction = "auto",
      opacity = 0.75))

mort_hb_easr 

# save the widget in a html file if needed.
saveWidget(mort_hb_easr, here("map_files/mort_hb_easr.html"))
```

## Council - Deaths

```{r}
mortality_ca <- read_csv(here("clean_data/mortality_ca.csv")) 

council_sf <- st_read(here::here("map_files/council_shapefile_scotland/pub_las.shp"))

council_sf <- st_transform(council_sf, "+proj=longlat +ellps=WGS84 +datum=WGS84")

council_sf_simplified <- rmapshaper::ms_simplify(input = council_sf,
                                           keep = 0.001,
                                           keep_shapes = TRUE)

rm(council_sf)

```

```{r}
mortality_ca_totals <- mortality_ca %>% 
  filter(ca != "S92000003",
         sex == "All",
         age == "All", 
         diagnosis == "Cerebrovascular Disease",
         year == 2021) %>% 
  select(-c("year", "ca", "age", "sex", "diagnosis", "hb", "hb_name")) %>% 
  mutate(ca_name = recode(ca_name, "Na h-Eileanan Siar" = "Eilean Siar"))

sf_ca_mort_data <- left_join(council_sf_simplified, mortality_ca_totals, 
                             by = c("local_auth" = "ca_name")) %>% 
  mutate(crude_rate = round(crude_rate, 0),
         easr = round(easr, 0))

#rm(mortality_ca, mortality_ca_totals, council_sf_simplified)


```


```{r}
# Prepare the text for tooltips:
mytext_mort_ca <- paste(
    "Health Board: ", sf_ca_mort_data$local_auth,"<br/>", 
    "EASR: ", sf_ca_mort_data$easr, "<br/>", 
    "Deaths: ", sf_ca_mort_data$number_of_deaths, 
    sep="") %>%
  lapply(htmltools::HTML)

# originally used colorQuantile but colorNumeric creates a continuous color range 
# for continous input which is what we have. 
pal_mort_ca <- colorNumeric(
  palette = "Purples",
  domain = sf_ca_mort_data$easr)

mort_ca_easr <- leaflet(sf_ca_mort_data) %>% 
  addTiles()  %>% 
  setView( lat=57, lng=-5 , zoom=6) %>%
  addPolygons(stroke = TRUE, 
              color = "black", 
              weight = 1,
              fillOpacity = 0.8, 
    #          smoothFactor = 0.5, 
    #          fillColor = ~colorQuantile("Purples", easr)(easr) ,
              fillColor = ~pal_mort_ca(easr),
    label = mytext_mort_ca,
    labelOptions = labelOptions( 
      style = list("font-weight" = "normal", padding = "3px 8px"), 
      textsize = "13px", 
      direction = "auto",
    opacity = 0.75))

mort_ca_easr 

# save the widget in a html file if needed.
saveWidget(mort_ca_easr, here("map_files/mort_ca_easr.html"))
```


